[Output]
ImageId=arch-rescue
Format=uki
OutputDirectory=mkosi.output
CompressOutput=false
SplitArtifacts=uki

[Build]
History=true

[Distribution]
Distribution=arch

[Content]
Hostname=arch-rescue
Bootloader=none
Bootable=false
Timezone=UTC
RootShell=/bin/bash
Keymap=us
Locale=C.UTF-8
MicrocodeHost=false
KernelModulesExclude=.*
KernelModulesInclude=
    fs/
    hid/
    input/
    dm-.*
    crypto/
    tpm/
    virtio
    usb/
    net/
    nvme
    ata/
    scsi/
    mmc/
Packages=
    base
    linux-lts
    linux-firmware
    arch-install-scripts
    btrfs-progs
    curl
    cryptsetup
    efibootmgr
    iptables
    libfido2
    pciutils
    sbctl
    snapper
    tpm2-tss
    rsync
    gum
    impala
    iwd
    util-linux
    dosfstools
    vim
    less
    man-pages
    mandoc
KernelCommandLine=
RemoveFiles=
    /usr/include/
    /usr/share/include
    /usr/share/pkgconfig
    /usr/lib/**/*.a
    /usr/share/locale
    /var/lib/pacman/sync/*
