write_logs = yes
log_file = /var/log/audit/audit.log
log_format = ENRICHED

max_log_file = 50
num_logs = 10
max_log_file_action = ROTATE

space_left = 2048
space_left_action = SYSLOG

admin_space_left = 1024
admin_space_left_action = SYSLOG

disk_full_action = SYSLOG
disk_error_action = SYSLOG
