bubblewrap
libsecret
xdg-dbus-proxy
audit
cryptsetup
e2fsprogs
btrfs-progs
efibootmgr
efitools
ldns
socat
strace
bpftrace
age
pwgen
mise
jq
nnn
trash-cli
openssh
tmux
git
wget
curl
tar
zip
unzip
tree
dust
btop
fastfetch
rsync
rclone
restic
snapper
snap-pac
gocryptfs
fuse2
fuse3
reflector
pacman-contrib
nftables
lsof
nmap
tcpdump
bash-completion
man-db
tpm2-tools
words
python-pip
gcr
oath-toolkit
qrencode
zbar
tailscale
iwd
impala
apparmor
sbctl
sudo
usbguard
vim
fwupd
zram-generator
