pacutils
lostfiles
audit
cryptsetup
btrfs-progs
efibootmgr
lsof
ldns
socat
tcpdump
age
pwgen
mise
jq
nnn
trash-cli
openssh
tmux
git
wget
curl
zip
unzip
tree
htop
fastfetch
rsync
rclone
restic
snapper
gocryptfs
fuse3
reflector
pacman-contrib
archiso
nftables
nmap
bash-completion
man-db
tpm2-tools
words
oath-toolkit
qrencode
zbar
tailscale
iwd
impala
apparmor
sbctl
usbguard
vim
fwupd
zram-generator
